apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: sample-express-app
        image: express-app
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
