apiVersion: v1
kind: Service
metadata:
  name: my-express-service
spec:
  type: NodePort
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30000
  sessionAffinity: None
