apiVersion: v1
kind: Pod
metadata:
  name: node-pod
spec:
  containers:
  - name: sampleapp
    image: sampleapp/v1
    command: ['sh', '-c', 'echo "Starting server at 80!"']
    # command: ["sh", "-c", "sleep 600"]
    command: ["tail", "-f", "/dev/null"]
    ports:
    - containerPort: 3000
    imagePullPolicy: IfNotPresent
