apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: sample-node-app
        image: sampleapp/v1
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
